# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxifishkaclient',
            name='info',
            field=models.CharField(default='', max_length=16384),
            preserve_default=False,
        ),
    ]
