# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0002_taxifishkaclient_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('tarif', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
        ),
    ]
