# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0006_auto_20170712_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='timezone',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
