# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-12 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0007_city_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='attrs',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
