# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-08 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0010_city_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, max_length=16384, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bots.TaxifishkaClient')),
            ],
        ),
    ]
