# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-09 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0012_juridicalclientgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxifishkaclient',
            name='client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
