# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-09 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0013_taxifishkaclient_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bots.TaxifishkaClient')),
            ],
        ),
    ]
