# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-09 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0014_clientfamily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxifishkaclient',
            name='client_id',
        ),
    ]
