# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-18 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0017_juridicalclientgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='tarif',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
