# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-19 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0018_auto_20170918_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='finished',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
