# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-23 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0020_orderhistory_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxifishkaclient',
            name='registered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
