# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-19 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0021_taxifishkaclient_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxifishkaclient',
            name='registered',
        ),
        migrations.AddField(
            model_name='taxifishkaclient',
            name='registered_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
