# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-07 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0022_auto_20171119_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('help_text', models.CharField(max_length=64000)),
                ('attrs', models.CharField(max_length=1024)),
                ('order_polling_period', models.IntegerField()),
            ],
        ),
    ]
