# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-07 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bots', '0023_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='attrs',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='help_text',
            field=models.CharField(blank=True, max_length=64000, null=True),
        ),
    ]
